In [49]:
import pandas as pd

In [50]:
data = pd.read_csv('amazon_product.csv')
data.head()

,Unnamed: 0,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_url,product_photo,...,is_best_seller,is_amazon_choice,is_prime,climate_pledge_friendly,sales_volume,delivery,has_variations,product_availability,unit_price,unit_count
0,0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,$169.99,USD,4.0,2929,https://www.amazon.com/dp/B0BQ118F2T,https://m.media-amazon.com/images/I/61K1Fz5Lxv...,...,False,False,True,False,6K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN
1,1,B0CTD47P22,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,$158.00,USD,4.2,135,https://www.amazon.com/dp/B0CTD47P22,https://m.media-amazon.com/images/I/51QhB2CfqS...,...,False,False,True,False,3K+ bought in past month,"FREE delivery Wed, Aug 7 Only 7 left in stock ...",False,Only 7 left in stock - order soon.,NaN,NaN
2,2,B0CHH6X6H2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,NaN,USD,3.9,205,https://www.amazon.com/dp/B0CHH6X6H2,https://m.media-amazon.com/images/I/812woqv69C...,...,False,False,True,False,2K+ bought in past month,"FREE delivery Tue, Aug 6",False,NaN,NaN,NaN
3,3,B0BZ9XNBRB,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,$499.00,USD,4.3,2248,https://www.amazon.com/dp/B0BZ9XNBRB,https://m.media-amazon.com/images/I/61r7cCpQPl...,...,False,False,False,False,10K+ bought in past month,FREE delivery Aug 6 - 8,True,NaN,NaN,NaN
4,4,B0CN1QSH8Q,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,NaN,USD,4.1,423,https://www.amazon.com/dp/B0CN1QSH8Q,https://m.media-amazon.com/images/I/61s0ZzwzSC...,...,False,False,True,True,3K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN

In [51]:
data.shape

(64, 22)

In [52]:
data.columns

Index(['Unnamed: 0', 'asin', 'product_title', 'product_price',
       'product_original_price', 'currency', 'product_star_rating',
       'product_num_ratings', 'product_url', 'product_photo',
       'product_num_offers', 'product_minimum_offer_price', 'is_best_seller',
       'is_amazon_choice', 'is_prime', 'climate_pledge_friendly',
       'sales_volume', 'delivery', 'has_variations', 'product_availability',
       'unit_price', 'unit_count'],
      dtype='str')

In [53]:
data.isna().sum()

Unnamed: 0                      0
asin                            0
product_title                   0
product_price                   0
product_original_price         37
currency                        0
product_star_rating            10
product_num_ratings             0
product_url                     0
product_photo                   0
product_num_offers              0
product_minimum_offer_price     0
is_best_seller                  0
is_amazon_choice                0
is_prime                        0
climate_pledge_friendly         0
sales_volume                    3
delivery                        1
has_variations                  0
product_availability           63
unit_price                     59
unit_count                     59
dtype: int64

In [54]:
columnsToDrop = ['Unnamed: 0', 'asin','product_url', 'product_photo',
       'product_num_offers','product_availability',
       'unit_price', 'unit_count']

data.drop(columns = columnsToDrop,inplace = True)

In [55]:
data.columns

Index(['product_title', 'product_price', 'product_original_price', 'currency',
       'product_star_rating', 'product_num_ratings',
       'product_minimum_offer_price', 'is_best_seller', 'is_amazon_choice',
       'is_prime', 'climate_pledge_friendly', 'sales_volume', 'delivery',
       'has_variations'],
      dtype='str')

In [56]:
data.isna().sum()

product_title                   0
product_price                   0
product_original_price         37
currency                        0
product_star_rating            10
product_num_ratings             0
product_minimum_offer_price     0
is_best_seller                  0
is_amazon_choice                0
is_prime                        0
climate_pledge_friendly         0
sales_volume                    3
delivery                        1
has_variations                  0
dtype: int64

In [57]:
data.duplicated().sum()

np.int64(0)

In [58]:
data['product_original_price'] = data['product_original_price'].fillna(0)

In [59]:
data.dropna(inplace=True)

In [60]:
data.isna().sum()

product_title                  0
product_price                  0
product_original_price         0
currency                       0
product_star_rating            0
product_num_ratings            0
product_minimum_offer_price    0
is_best_seller                 0
is_amazon_choice               0
is_prime                       0
climate_pledge_friendly        0
sales_volume                   0
delivery                       0
has_variations                 0
dtype: int64

In [61]:
data.info()

<class 'pandas.DataFrame'>
Index: 53 entries, 0 to 63
Data columns (total 14 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   product_title                53 non-null     str
 1   product_price                53 non-null     str
 2   product_original_price       53 non-null     object
 3   currency                     53 non-null     str
 4   product_star_rating          53 non-null     float64
 5   product_num_ratings          53 non-null     int64
 6   product_minimum_offer_price  53 non-null     str
 7   is_best_seller               53 non-null     bool
 8   is_amazon_choice             53 non-null     bool
 9   is_prime                     53 non-null     bool
 10  climate_pledge_friendly      53 non-null     bool
 11  sales_volume                 53 non-null     str
 12  delivery                     53 non-null     str
 13  has_variations               53 non-null     bool
dtypes: bool(5), float64(1), int64(1), object(1), str(6)
memory usage: 4.4+ KB

In [62]:
data.head()

,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_minimum_offer_price,is_best_seller,is_amazon_choice,is_prime,climate_pledge_friendly,sales_volume,delivery,has_variations
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,$169.99,USD,4.0,2929,$64.89,False,False,True,False,6K+ bought in past month,"FREE delivery Tue, Aug 6",True
1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,$158.00,USD,4.2,135,$145.87,False,False,True,False,3K+ bought in past month,"FREE delivery Wed, Aug 7 Only 7 left in stock ...",False
2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,0,USD,3.9,205,$49.88,False,False,True,False,2K+ bought in past month,"FREE delivery Tue, Aug 6",False
3,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,$499.00,USD,4.3,2248,$289.99,False,False,False,False,10K+ bought in past month,FREE delivery Aug 6 - 8,True
4,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,0,USD,4.1,423,$150.09,False,False,True,True,3K+ bought in past month,"FREE delivery Tue, Aug 6",True

In [63]:
data['product_price'] = data['product_price'].str.strip()
data['product_price'] = data['product_price'].str.replace(' ',"")
data['product_price'] = data['product_price'].str.replace('$',"")
data['product_price'] = data['product_price'].astype(float)

In [64]:
data.info()

<class 'pandas.DataFrame'>
Index: 53 entries, 0 to 63
Data columns (total 14 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   product_title                53 non-null     str
 1   product_price                53 non-null     float64
 2   product_original_price       53 non-null     object
 3   currency                     53 non-null     str
 4   product_star_rating          53 non-null     float64
 5   product_num_ratings          53 non-null     int64
 6   product_minimum_offer_price  53 non-null     str
 7   is_best_seller               53 non-null     bool
 8   is_amazon_choice             53 non-null     bool
 9   is_prime                     53 non-null     bool
 10  climate_pledge_friendly      53 non-null     bool
 11  sales_volume                 53 non-null     str
 12  delivery                     53 non-null     str
 13  has_variations               53 non-null     bool
dtypes: bool(5), float64(2), int64(1), object(1), str(5)
memory usage: 4.4+ KB

In [65]:
data.head()

,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_minimum_offer_price,is_best_seller,is_amazon_choice,is_prime,climate_pledge_friendly,sales_volume,delivery,has_variations
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,99.99,$169.99,USD,4.0,2929,$64.89,False,False,True,False,6K+ bought in past month,"FREE delivery Tue, Aug 6",True
1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",149.74,$158.00,USD,4.2,135,$145.87,False,False,True,False,3K+ bought in past month,"FREE delivery Wed, Aug 7 Only 7 left in stock ...",False
2,Total by Verizon | Samsung Galaxy A03s | Locke...,49.88,0,USD,3.9,205,$49.88,False,False,True,False,2K+ bought in past month,"FREE delivery Tue, Aug 6",False
3,Google Pixel 7a - Unlocked Android Cell Phone ...,335.00,$499.00,USD,4.3,2248,$289.99,False,False,False,False,10K+ bought in past month,FREE delivery Aug 6 - 8,True
4,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",199.99,0,USD,4.1,423,$150.09,False,False,True,True,3K+ bought in past month,"FREE delivery Tue, Aug 6",True